<?php
  $observer = 'universal_variable_main/observer';
  $mage = Mage::getSingleton($observer);
  $version     = $mage->getVersion();
  $page        = $mage->getPage();
  $user        = $mage->getUser();
  $product     = $mage->getProduct();
  $basket      = $mage->getBasket();
  $listing     = $mage->getListing();
  $transaction = $mage->getTransaction();
?>

<!-- Universal Variable Start -->
<script type="text/javascript">
  window.universal_variable = window.universal_variable || {};
  window.universal_variable.version      = <?php echo json_encode($version) ?>;
  window.universal_variable.page         = <?php echo json_encode($page)    ?>;
  window.universal_variable.user         = <?php echo json_encode($user)    ?>;
  <?php if ($product) : ?>
  window.universal_variable.product      = <?php echo json_encode($product) ?>;
  <?php endif?>
  <?php if ($basket) : ?>
  window.universal_variable.basket       = <?php echo json_encode($basket)  ?>;
  <?php endif ?>
  <?php if ($listing) : ?>
  window.universal_variable.listing      = <?php echo json_encode($listing) ?>;
  <?php endif ?>
  <?php if ($transaction) : ?>
  window.universal_variable.transaction  = <?php echo json_encode($transaction)  ?>;
  <?php endif ?>
</script>
<!-- Universal Variable End -->